server:
  port: 8085
spring:
  application:
    name: sidi-abdlatif-examen-jee
  datasource:
    url: jdbc:mysql://localhost:3306/sidi_abdlatif_examen_jee_db?createDatabaseIfNotExist=true
    username: nabgha
    password: "44026676"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
